# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

CCACHE=/usr/bin/ccache
CU=/usr/bin/clang
CXX=/usr/bin/gcc
CC=/usr/bin/gcc
AS=/usr/bin/gcc
MXX=/usr/bin/gcc
MM=/usr/bin/gcc

AR=/usr/bin/ar
LD=/usr/bin/g++
SH=/usr/bin/g++

wiggle_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -Iinclude/greedy
wiggle_LDFLAGS=-m64 -Lbuild/linux/x86_64/release -s -llibwiggle
libcontent_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -Iinclude/page -Iinclude/content
libcontent_ARFLAGS=-cr
libwiggle_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -Iinclude/greedy
libwiggle_ARFLAGS=-cr
assign_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -Iinclude/greedy
assign_LDFLAGS=-m64 -Lbuild/linux/x86_64/release -s -llibassign
libassign_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -Iinclude/greedy
libassign_ARFLAGS=-cr
libpage_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -Iinclude/page
libpage_ARFLAGS=-cr
pageReplace_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3
pageReplace_LDFLAGS=-m64 -s
libbank_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -Iinclude/banker
libbank_ARFLAGS=-cr
testBank_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -Iinclude/banker
testBank_LDFLAGS=-m64 -Lbuild/linux/x86_64/release -s -llibbank
main_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -Iinclude/content
main_LDFLAGS=-m64 -Lbuild/linux/x86_64/release -s -llibcontent -llibpage

default:  wiggle libcontent libwiggle assign libassign libpage pageReplace libbank testBank main

all:  wiggle libcontent libwiggle assign libassign libpage pageReplace libbank testBank main

.PHONY: default all  wiggle libcontent libwiggle assign libassign libpage pageReplace libbank testBank main

wiggle: build/linux/x86_64/release/wiggle
build/linux/x86_64/release/wiggle: build/linux/x86_64/release/liblibwiggle.a build/.objs/wiggle/linux/x86_64/release/src/greedy/wiggle.cpp.o
	@echo linking.release wiggle
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/wiggle build/.objs/wiggle/linux/x86_64/release/src/greedy/wiggle.cpp.o $(wiggle_LDFLAGS) > build/.build.log 2>&1

build/.objs/wiggle/linux/x86_64/release/src/greedy/wiggle.cpp.o: src/greedy/wiggle.cpp
	@echo ccache compiling.release src/greedy/wiggle.cpp
	@mkdir -p build/.objs/wiggle/linux/x86_64/release/src/greedy
	@$(CCACHE) $(CXX) -c $(wiggle_CXXFLAGS) -o build/.objs/wiggle/linux/x86_64/release/src/greedy/wiggle.cpp.o src/greedy/wiggle.cpp > build/.build.log 2>&1

libcontent: build/linux/x86_64/release/liblibcontent.a
build/linux/x86_64/release/liblibcontent.a: build/linux/x86_64/release/liblibpage.a build/.objs/libcontent/linux/x86_64/release/lib/content/context.cpp.o
	@echo linking.release liblibcontent.a
	@mkdir -p build/linux/x86_64/release
	@$(AR) $(libcontent_ARFLAGS) build/linux/x86_64/release/liblibcontent.a build/.objs/libcontent/linux/x86_64/release/lib/content/context.cpp.o > build/.build.log 2>&1

build/.objs/libcontent/linux/x86_64/release/lib/content/context.cpp.o: lib/content/context.cpp
	@echo ccache compiling.release lib/content/context.cpp
	@mkdir -p build/.objs/libcontent/linux/x86_64/release/lib/content
	@$(CCACHE) $(CXX) -c $(libcontent_CXXFLAGS) -o build/.objs/libcontent/linux/x86_64/release/lib/content/context.cpp.o lib/content/context.cpp > build/.build.log 2>&1

libwiggle: build/linux/x86_64/release/liblibwiggle.a
build/linux/x86_64/release/liblibwiggle.a: build/.objs/libwiggle/linux/x86_64/release/lib/greedy/WiggleSubsequence.cpp.o
	@echo linking.release liblibwiggle.a
	@mkdir -p build/linux/x86_64/release
	@$(AR) $(libwiggle_ARFLAGS) build/linux/x86_64/release/liblibwiggle.a build/.objs/libwiggle/linux/x86_64/release/lib/greedy/WiggleSubsequence.cpp.o > build/.build.log 2>&1

build/.objs/libwiggle/linux/x86_64/release/lib/greedy/WiggleSubsequence.cpp.o: lib/greedy/WiggleSubsequence.cpp
	@echo ccache compiling.release lib/greedy/WiggleSubsequence.cpp
	@mkdir -p build/.objs/libwiggle/linux/x86_64/release/lib/greedy
	@$(CCACHE) $(CXX) -c $(libwiggle_CXXFLAGS) -o build/.objs/libwiggle/linux/x86_64/release/lib/greedy/WiggleSubsequence.cpp.o lib/greedy/WiggleSubsequence.cpp > build/.build.log 2>&1

assign: build/linux/x86_64/release/assign
build/linux/x86_64/release/assign: build/linux/x86_64/release/liblibassign.a build/.objs/assign/linux/x86_64/release/src/greedy/wiggle.cpp.o build/.objs/assign/linux/x86_64/release/src/greedy/Assign.cpp.o
	@echo linking.release assign
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/assign build/.objs/assign/linux/x86_64/release/src/greedy/wiggle.cpp.o build/.objs/assign/linux/x86_64/release/src/greedy/Assign.cpp.o $(assign_LDFLAGS) > build/.build.log 2>&1

build/.objs/assign/linux/x86_64/release/src/greedy/wiggle.cpp.o: src/greedy/wiggle.cpp
	@echo ccache compiling.release src/greedy/wiggle.cpp
	@mkdir -p build/.objs/assign/linux/x86_64/release/src/greedy
	@$(CCACHE) $(CXX) -c $(assign_CXXFLAGS) -o build/.objs/assign/linux/x86_64/release/src/greedy/wiggle.cpp.o src/greedy/wiggle.cpp > build/.build.log 2>&1

build/.objs/assign/linux/x86_64/release/src/greedy/Assign.cpp.o: src/greedy/Assign.cpp
	@echo ccache compiling.release src/greedy/Assign.cpp
	@mkdir -p build/.objs/assign/linux/x86_64/release/src/greedy
	@$(CCACHE) $(CXX) -c $(assign_CXXFLAGS) -o build/.objs/assign/linux/x86_64/release/src/greedy/Assign.cpp.o src/greedy/Assign.cpp > build/.build.log 2>&1

libassign: build/linux/x86_64/release/liblibassign.a
build/linux/x86_64/release/liblibassign.a: build/.objs/libassign/linux/x86_64/release/lib/greedy/AssignCookie.cpp.o build/.objs/libassign/linux/x86_64/release/lib/greedy/WiggleSubsequence.cpp.o
	@echo linking.release liblibassign.a
	@mkdir -p build/linux/x86_64/release
	@$(AR) $(libassign_ARFLAGS) build/linux/x86_64/release/liblibassign.a build/.objs/libassign/linux/x86_64/release/lib/greedy/AssignCookie.cpp.o build/.objs/libassign/linux/x86_64/release/lib/greedy/WiggleSubsequence.cpp.o > build/.build.log 2>&1

build/.objs/libassign/linux/x86_64/release/lib/greedy/AssignCookie.cpp.o: lib/greedy/AssignCookie.cpp
	@echo ccache compiling.release lib/greedy/AssignCookie.cpp
	@mkdir -p build/.objs/libassign/linux/x86_64/release/lib/greedy
	@$(CCACHE) $(CXX) -c $(libassign_CXXFLAGS) -o build/.objs/libassign/linux/x86_64/release/lib/greedy/AssignCookie.cpp.o lib/greedy/AssignCookie.cpp > build/.build.log 2>&1

build/.objs/libassign/linux/x86_64/release/lib/greedy/WiggleSubsequence.cpp.o: lib/greedy/WiggleSubsequence.cpp
	@echo ccache compiling.release lib/greedy/WiggleSubsequence.cpp
	@mkdir -p build/.objs/libassign/linux/x86_64/release/lib/greedy
	@$(CCACHE) $(CXX) -c $(libassign_CXXFLAGS) -o build/.objs/libassign/linux/x86_64/release/lib/greedy/WiggleSubsequence.cpp.o lib/greedy/WiggleSubsequence.cpp > build/.build.log 2>&1

libpage: build/linux/x86_64/release/liblibpage.a
build/linux/x86_64/release/liblibpage.a: build/.objs/libpage/linux/x86_64/release/lib/page/PageReplace.cpp.o
	@echo linking.release liblibpage.a
	@mkdir -p build/linux/x86_64/release
	@$(AR) $(libpage_ARFLAGS) build/linux/x86_64/release/liblibpage.a build/.objs/libpage/linux/x86_64/release/lib/page/PageReplace.cpp.o > build/.build.log 2>&1

build/.objs/libpage/linux/x86_64/release/lib/page/PageReplace.cpp.o: lib/page/PageReplace.cpp
	@echo ccache compiling.release lib/page/PageReplace.cpp
	@mkdir -p build/.objs/libpage/linux/x86_64/release/lib/page
	@$(CCACHE) $(CXX) -c $(libpage_CXXFLAGS) -o build/.objs/libpage/linux/x86_64/release/lib/page/PageReplace.cpp.o lib/page/PageReplace.cpp > build/.build.log 2>&1

pageReplace: build/linux/x86_64/release/pageReplace
build/linux/x86_64/release/pageReplace: build/.objs/pageReplace/linux/x86_64/release/src/page/PageReplace.cpp.o
	@echo linking.release pageReplace
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/pageReplace build/.objs/pageReplace/linux/x86_64/release/src/page/PageReplace.cpp.o $(pageReplace_LDFLAGS) > build/.build.log 2>&1

build/.objs/pageReplace/linux/x86_64/release/src/page/PageReplace.cpp.o: src/page/PageReplace.cpp
	@echo ccache compiling.release src/page/PageReplace.cpp
	@mkdir -p build/.objs/pageReplace/linux/x86_64/release/src/page
	@$(CCACHE) $(CXX) -c $(pageReplace_CXXFLAGS) -o build/.objs/pageReplace/linux/x86_64/release/src/page/PageReplace.cpp.o src/page/PageReplace.cpp > build/.build.log 2>&1

libbank: build/linux/x86_64/release/liblibbank.a
build/linux/x86_64/release/liblibbank.a: build/.objs/libbank/linux/x86_64/release/lib/banker/Banker.cpp.o
	@echo linking.release liblibbank.a
	@mkdir -p build/linux/x86_64/release
	@$(AR) $(libbank_ARFLAGS) build/linux/x86_64/release/liblibbank.a build/.objs/libbank/linux/x86_64/release/lib/banker/Banker.cpp.o > build/.build.log 2>&1

build/.objs/libbank/linux/x86_64/release/lib/banker/Banker.cpp.o: lib/banker/Banker.cpp
	@echo ccache compiling.release lib/banker/Banker.cpp
	@mkdir -p build/.objs/libbank/linux/x86_64/release/lib/banker
	@$(CCACHE) $(CXX) -c $(libbank_CXXFLAGS) -o build/.objs/libbank/linux/x86_64/release/lib/banker/Banker.cpp.o lib/banker/Banker.cpp > build/.build.log 2>&1

testBank: build/linux/x86_64/release/testBank
build/linux/x86_64/release/testBank: build/linux/x86_64/release/liblibbank.a build/.objs/testBank/linux/x86_64/release/src/TestBack.cpp.o
	@echo linking.release testBank
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/testBank build/.objs/testBank/linux/x86_64/release/src/TestBack.cpp.o $(testBank_LDFLAGS) > build/.build.log 2>&1

build/.objs/testBank/linux/x86_64/release/src/TestBack.cpp.o: src/TestBack.cpp
	@echo ccache compiling.release src/TestBack.cpp
	@mkdir -p build/.objs/testBank/linux/x86_64/release/src
	@$(CCACHE) $(CXX) -c $(testBank_CXXFLAGS) -o build/.objs/testBank/linux/x86_64/release/src/TestBack.cpp.o src/TestBack.cpp > build/.build.log 2>&1

main: build/linux/x86_64/release/main
build/linux/x86_64/release/main: build/linux/x86_64/release/liblibcontent.a build/.objs/main/linux/x86_64/release/src/fifo/main.cpp.o
	@echo linking.release main
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/main build/.objs/main/linux/x86_64/release/src/fifo/main.cpp.o $(main_LDFLAGS) > build/.build.log 2>&1

build/.objs/main/linux/x86_64/release/src/fifo/main.cpp.o: src/fifo/main.cpp
	@echo ccache compiling.release src/fifo/main.cpp
	@mkdir -p build/.objs/main/linux/x86_64/release/src/fifo
	@$(CCACHE) $(CXX) -c $(main_CXXFLAGS) -o build/.objs/main/linux/x86_64/release/src/fifo/main.cpp.o src/fifo/main.cpp > build/.build.log 2>&1

clean:  clean_wiggle clean_libcontent clean_libwiggle clean_assign clean_libassign clean_libpage clean_pageReplace clean_libbank clean_testBank clean_main

clean_wiggle:  clean_libwiggle
	@rm -rf build/linux/x86_64/release/wiggle
	@rm -rf build/linux/x86_64/release/wiggle.sym
	@rm -rf build/.objs/wiggle/linux/x86_64/release/src/greedy/wiggle.cpp.o

clean_libcontent:  clean_libpage
	@rm -rf build/linux/x86_64/release/liblibcontent.a
	@rm -rf build/linux/x86_64/release/libcontent.sym
	@rm -rf build/.objs/libcontent/linux/x86_64/release/lib/content/context.cpp.o

clean_libwiggle: 
	@rm -rf build/linux/x86_64/release/liblibwiggle.a
	@rm -rf build/linux/x86_64/release/libwiggle.sym
	@rm -rf build/.objs/libwiggle/linux/x86_64/release/lib/greedy/WiggleSubsequence.cpp.o

clean_assign:  clean_libassign
	@rm -rf build/linux/x86_64/release/assign
	@rm -rf build/linux/x86_64/release/assign.sym
	@rm -rf build/.objs/assign/linux/x86_64/release/src/greedy/wiggle.cpp.o
	@rm -rf build/.objs/assign/linux/x86_64/release/src/greedy/Assign.cpp.o

clean_libassign: 
	@rm -rf build/linux/x86_64/release/liblibassign.a
	@rm -rf build/linux/x86_64/release/libassign.sym
	@rm -rf build/.objs/libassign/linux/x86_64/release/lib/greedy/AssignCookie.cpp.o
	@rm -rf build/.objs/libassign/linux/x86_64/release/lib/greedy/WiggleSubsequence.cpp.o

clean_libpage: 
	@rm -rf build/linux/x86_64/release/liblibpage.a
	@rm -rf build/linux/x86_64/release/libpage.sym
	@rm -rf build/.objs/libpage/linux/x86_64/release/lib/page/PageReplace.cpp.o

clean_pageReplace: 
	@rm -rf build/linux/x86_64/release/pageReplace
	@rm -rf build/linux/x86_64/release/pageReplace.sym
	@rm -rf build/.objs/pageReplace/linux/x86_64/release/src/page/PageReplace.cpp.o

clean_libbank: 
	@rm -rf build/linux/x86_64/release/liblibbank.a
	@rm -rf build/linux/x86_64/release/libbank.sym
	@rm -rf build/.objs/libbank/linux/x86_64/release/lib/banker/Banker.cpp.o

clean_testBank:  clean_libbank
	@rm -rf build/linux/x86_64/release/testBank
	@rm -rf build/linux/x86_64/release/testBank.sym
	@rm -rf build/.objs/testBank/linux/x86_64/release/src/TestBack.cpp.o

clean_main:  clean_libcontent
	@rm -rf build/linux/x86_64/release/main
	@rm -rf build/linux/x86_64/release/main.sym
	@rm -rf build/.objs/main/linux/x86_64/release/src/fifo/main.cpp.o

